"""empty message

Revision ID: 9eb32d3d80b0
Revises: 
Create Date: 2018-10-31 16:47:08.377689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb32d3d80b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('p_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('p_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_name', sa.String(length=32), nullable=True),
    sa.Column('_u_password', sa.String(length=256), nullable=True),
    sa.Column('is_super', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('u_name')
    )
    op.create_table('user_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_permission_id', sa.Integer(), nullable=True),
    sa.Column('u_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['u_permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['u_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permission')
    op.drop_table('user')
    op.drop_table('permission')
    # ### end Alembic commands ###
