"""empty message

Revision ID: b22d465f65e9
Revises: 9eb32d3d80b0
Create Date: 2018-11-01 10:28:07.899694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22d465f65e9'
down_revision = '9eb32d3d80b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('b_content', sa.String(length=1000), nullable=True),
    sa.Column('b_title', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###
