"""empty message

Revision ID: fd831d35d89a
Revises: b22d465f65e9
Create Date: 2018-11-01 10:29:33.160508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd831d35d89a'
down_revision = 'b22d465f65e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('b_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog', 'user', ['b_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_column('blog', 'b_user')
    # ### end Alembic commands ###
